import 'package:nutrial/models/gm_model.dart';
import 'package:nutrial/models/piece_model.dart';

class CaloriesDB {
  final List<dynamic> calories = [
    PieceModel(itemName: 'Egg_White', itemCalories: 17, itemQuantity: 'piece'),

    GmsModel(
        itemName: 'Boiled_Chicken_Skinless_Breast',
        itemCalories: 155,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Boiled_Chicken_Skinless_thigh',
        itemCalories: 195,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Boiled_lean_Beef',
        itemCalories: 150,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Chicken_liver', itemCalories: 180, itemQuantity: '100 gms'),
    GmsModel(itemName: 'Egg_White', itemCalories: 17, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Grilled_Bolty', itemCalories: 140, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Grilled_Bory', itemCalories: 150, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Grilled_calamari',
        itemCalories: 140,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Grilled_Chicken_Skinless_Breast',
        itemCalories: 170,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Grilled_Chicken_Skinless_thigh',
        itemCalories: 210,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Grilled_Crab', itemCalories: 100, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Grilled_Denes', itemCalories: 90, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Grilled_Dove_hamam',
        itemCalories: 220,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Grilled_fillet_keshr_bayad',
        itemCalories: 100,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Grilled_lean_beef_or_steak',
        itemCalories: 190,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Grilled_Mackrel',
        itemCalories: 270,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Grilled_Mackrel_liver',
        itemCalories: 200,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Grilled_minced_beef_or_kofta',
        itemCalories: 280,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Grilled_moussa', itemCalories: 100, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Grilled_rabbit', itemCalories: 190, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Grilled_salmon', itemCalories: 170, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Grilled_shrimps',
        itemCalories: 100,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Grilled_skinless_duck',
        itemCalories: 205,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Grilled_turkey_skinless_breast',
        itemCalories: 150,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Grilled_turkey_skinless_thigh',
        itemCalories: 170,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Grilled_wakar', itemCalories: 100, itemQuantity: '100 gms'),
    GmsModel(itemName: 'Sardines', itemCalories: 220, itemQuantity: '100 gms'),

    GmsModel(
        itemName: 'water_Canned_light_tuna',
        itemCalories: 200,
        itemQuantity: 'can'),

    GmsModel(
        itemName: 'Air_popped_Corn',
        itemCalories: 390,
        itemQuantity: '100 gms'),
    GmsModel(itemName: 'Apple', itemCalories: 60, itemQuantity: '100 gms'),
    GmsModel(itemName: 'Apricot', itemCalories: 50, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Aresh_Cheese', itemCalories: 110, itemQuantity: '100 gms'),
    GmsModel(itemName: 'Arsya', itemCalories: 250, itemQuantity: '100 gms'),
    GmsModel(itemName: 'Artichoke', itemCalories: 50, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Avocado_(fats)', itemCalories: 180, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Balady_Bread', itemCalories: 300, itemQuantity: '100 gms'),
    GmsModel(itemName: 'Banana', itemCalories: 95, itemQuantity: '100 gms'),

    GmsModel(
        itemName: 'BBQ_Sauce_(12g)',
        itemCalories: 25,
        itemQuantity: 'teaspoon'),
    GmsModel(itemName: 'Beets', itemCalories: 60, itemQuantity: '100 gms'),
    GmsModel(itemName: 'Berries', itemCalories: 60, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Boiled_Beans_Fool',
        itemCalories: 120,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Boiled_Chickpeas',
        itemCalories: 180,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Boiled_Freek', itemCalories: 130, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Boiled_Green_peas',
        itemCalories: 90,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Boiled_Lupine', itemCalories: 120, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Boiled_pasta', itemCalories: 160, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Boiled_potato', itemCalories: 100, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Boiled_ricc', itemCalories: 130, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Boiled_taro', itemCalories: 150, itemQuantity: '100 gms'),
    GmsModel(itemName: 'Broccoli', itemCalories: 35, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Butter_(fats)', itemCalories: 900, itemQuantity: '100 gms'),
    GmsModel(itemName: 'Cabbage', itemCalories: 30, itemQuantity: '100 gms'),
    GmsModel(itemName: 'Cantaloupe', itemCalories: 50, itemQuantity: '100 gms'),

    GmsModel(itemName: 'Carrot', itemCalories: 30, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Cauliflower', itemCalories: 35, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Cheddar_cheese(fats)',
        itemCalories: 400,
        itemQuantity: '100 gms'),
    GmsModel(itemName: 'Cherries', itemCalories: 60, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Chia_Seeds', itemCalories: 500, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Coconut_(fats)', itemCalories: 370, itemQuantity: '100 gms'),

    GmsModel(
        itemName: 'Coconut_milk_(fats)',
        itemCalories: 140,
        itemQuantity: '100 ml'),
    GmsModel(
        itemName: 'Coloured_pepper', itemCalories: 35, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Corn_oil_(fats)',
        itemCalories: 45,
        itemQuantity: 'teaspoon'),
    GmsModel(itemName: 'Date', itemCalories: 300, itemQuantity: '100 gms'),
    GmsModel(itemName: 'Edamame', itemCalories: 130, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Egg_Yolk_(fats)', itemCalories: 70, itemQuantity: 'piece'),
    GmsModel(itemName: 'Eggplant', itemCalories: 40, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Flaxseed_Oil_(fats)',
        itemCalories: 45,
        itemQuantity: 'teaspoon'),
    GmsModel(
        itemName: 'Fresh_Orange_juice',
        itemCalories: 55,
        itemQuantity: '100 ml'),
    GmsModel(
        itemName: 'Full_cream_milk', itemCalories: 70, itemQuantity: '100 ml'),
    GmsModel(
        itemName: 'Full_Cream_Yogurt(105g)',
        itemCalories: 70,
        itemQuantity: 'smallcup'),
    GmsModel(itemName: 'Garlic_Clove', itemCalories: 5, itemQuantity: 'piece'),
    GmsModel(
        itemName: 'Gouda_cheese_(fats)',
        itemCalories: 380,
        itemQuantity: '100 gms'),
    GmsModel(itemName: 'Grapefruit', itemCalories: 45, itemQuantity: '100 gms'),
    GmsModel(itemName: 'Grapes', itemCalories: 70, itemQuantity: '100 gms'),
    GmsModel(itemName: 'Guava', itemCalories: 70, itemQuantity: '100 gms'),

    GmsModel(
        itemName: 'Half_Cream_MILK', itemCalories: 55, itemQuantity: '100 ml'),
    GmsModel(itemName: 'Harankash', itemCalories: 60, itemQuantity: '100 gms'),
    GmsModel(itemName: 'Hazelnuts', itemCalories: 750, itemQuantity: '100 gms'),
    GmsModel(itemName: 'Honey(8g)', itemCalories: 30, itemQuantity: 'teaspoon'),
    GmsModel(itemName: 'jam_diet', itemCalories: 250, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'ketchuo(12g)', itemCalories: 15, itemQuantity: 'teaspoon'),
    GmsModel(itemName: 'kiwi', itemCalories: 65, itemQuantity: '100 gms'),
    GmsModel(itemName: 'lemon', itemCalories: 17, itemQuantity: 'piece'),
    GmsModel(
        itemName: 'lemon_greek_yogurt(105g)',
        itemCalories: 55,
        itemQuantity: 'smallcup'),

    GmsModel(
        itemName: 'Light_White_Cheese',
        itemCalories: 180,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Light_yogurt(105g)',
        itemCalories: 50,
        itemQuantity: 'smallcup'),
    GmsModel(itemName: 'Mango', itemCalories: 80, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'mayonnaise_light(10g)(fats)',
        itemCalories: 35,
        itemQuantity: 'teaspoon'),
    GmsModel(itemName: 'Molasses', itemCalories: 25, itemQuantity: 'teaspoon'),
    GmsModel(
        itemName: 'Moarella_Cheese',
        itemCalories: 300,
        itemQuantity: '100 gms'),
    GmsModel(itemName: 'Mshmsheya', itemCalories: 250, itemQuantity: '100 gms'),
    GmsModel(itemName: 'Mushrooms', itemCalories: 40, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Olive_Oil(fats)',
        itemCalories: 45,
        itemQuantity: 'teaspoon'),
    GmsModel(itemName: 'Olive_(fats)', itemCalories: 6, itemQuantity: 'peice'),
    GmsModel(itemName: 'Onions', itemCalories: 40, itemQuantity: '100 gms'),
    GmsModel(itemName: 'Orange', itemCalories: 50, itemQuantity: '100 gms'),
    GmsModel(itemName: 'Peach', itemCalories: 40, itemQuantity: '100 gms'),
    GmsModel(itemName: 'Pear', itemCalories: 60, itemQuantity: '100 gms'),
    GmsModel(itemName: 'Pineapple', itemCalories: 60, itemQuantity: '100 gms'),
    GmsModel(itemName: 'plum', itemCalories: 60, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'pomegranates', itemCalories: 85, itemQuantity: '100 gms'),

    GmsModel(
        itemName: 'pomegranates_molasses',
        itemCalories: 25,
        itemQuantity: 'teaspoon'),
    GmsModel(itemName: 'pumpkin', itemCalories: 30, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'pumpkin_seeds', itemCalories: 500, itemQuantity: '100 gms'),
    GmsModel(itemName: 'Raisins', itemCalories: 300, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Raw_ALmonds_(fats)',
        itemCalories: 580,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Raw_Belila', itemCalories: 380, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Raw_Cashew(fats)',
        itemCalories: 550,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Raw_Lentils', itemCalories: 360, itemQuantity: '100 gms'),
    GmsModel(itemName: 'Raw_Oats', itemCalories: 380, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Raw_Peanut_butter(fats)',
        itemCalories: 580,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Raw_Peanuts(fats)',
        itemCalories: 550,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Raw_pecan(fats)',
        itemCalories: 700,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Raw_pistachio(fats)',
        itemCalories: 560,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Raw_Quinoa', itemCalories: 387, itemQuantity: '100 gms'),

    GmsModel(
        itemName: 'Raw_Walnuts(fats)',
        itemCalories: 660,
        itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Romy_Cheese(fats)',
        itemCalories: 410,
        itemQuantity: '100 gms'),

    GmsModel(
        itemName: 'Skimmed_milk', itemCalories: 35, itemQuantity: '100 ml'),
    GmsModel(itemName: 'Strawberry', itemCalories: 40, itemQuantity: '100 gms'),
    GmsModel(itemName: 'Suger(4g)', itemCalories: 17, itemQuantity: 'teaspoon'),
    GmsModel(
        itemName: 'Sunflower_oil(fats)',
        itemCalories: 45,
        itemQuantity: 'teaspoon'),

    GmsModel(
        itemName: 'Sunflower_seeds_(fats)',
        itemCalories: 600,
        itemQuantity: '100 gms'),
    GmsModel(itemName: 'Sweet_corn', itemCalories: 90, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Sweet_potato', itemCalories: 90, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Tahini(5g)(fats)',
        itemCalories: 45,
        itemQuantity: 'teaspoon'),
    GmsModel(itemName: 'Tangerine', itemCalories: 65, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Teen_barshomy', itemCalories: 70, itemQuantity: 'piece'),
    GmsModel(itemName: 'Teen_shoky', itemCalories: 45, itemQuantity: 'piece'),
    GmsModel(itemName: 'Tomato', itemCalories: 20, itemQuantity: '100 gms'),
    GmsModel(itemName: 'Watermelon', itemCalories: 35, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'White_beans', itemCalories: 150, itemQuantity: '100 gms'),
    GmsModel(
        itemName: 'Whole_Wheat_brown_toast',
        itemCalories: 75,
        itemQuantity: 'piece'),
    GmsModel(
        itemName: 'Whole_wheat_flour',
        itemCalories: 400,
        itemQuantity: '100 gms'),

    // CanModel(itemName: 'حليب كامل الدسم ',itemCalories: 150),
    // CanModel(itemName: 'حليب قليل الدسم %1',itemCalories: 102),
    // CanModel(itemName: 'حليب البقر',itemCalories: 157),
    // CanModel(itemName: 'حليب الماعز',itemCalories: 264),
    // GmsModel(itemName: 'حليب مكثف محىل " علب"',itemCalories: 123),
    // SmallCupModel(itemName: 'حليب بودركامل الدسم',itemCalories: 635),
    // SmallCupModel(itemName: 'حليب بودرخالي الدسم',itemCalories: 435),
    // CanModel(itemName: 'حليب بالشوكوالتة كامل الدسم',itemCalories: 208),
    // CanModel(itemName: 'حليب بالفراولة',itemCalories: 244),
    // PieceModel(itemName: 'جبنة شيدر شرائح',itemCalories: 114),
    // GmsModel(itemName: 'جبنة فيتا',itemCalories: 75),
    // GmsModel(itemName: 'جبنة فونيتا',itemCalories: 110),
    // GmsModel(itemName: 'جبنة جودا',itemCalories: 101),
    //
    // GmsModel(itemName: 'جبنة موزاريلا "',itemCalories: 80),
    // GmsModel(itemName: 'جبنة كرافت " كاسات "',itemCalories: 80),
    // GmsModel(itemName: 'جبنة إيدام',itemCalories: 98),
    // GmsModel(itemName: 'جبنة زرقاء',itemCalories: 104),
    // GmsModel(itemName: 'جبنة الهارفاتي',itemCalories: 116),
    // GmsModel(itemName: 'جبنة باسكربوني',itemCalories: 128),
    // SmallCupModel(itemName: 'جبنة ريكوتا " حليبكامل الدسم "',itemCalories: 216),
    // SmallCupModel(itemName: 'جبنة ريكوتا حليب مقشود جزئيا',itemCalories: 171),
    // GmsModel(itemName: 'جبنة بارميزان',itemCalories: 130),
    // GmsModel(itemName: 'جبنة كممبرت',itemCalories: 86),
    // GmsModel(itemName: 'جبنة قريش',itemCalories: 99),
    // GmsModel(itemName: 'جبنة عكاوي',itemCalories: 289),
    //
    // SmallCupModel(itemName: 'عصير تفاح',itemCalories: 60),
    // SmallCupModel(itemName: 'عصير مشمش معلب',itemCalories: 72),
    // SmallCupModel(itemName: 'عصير عنب معلب',itemCalories: 78),
    // TeaSpoonModel(itemName: 'عصير ليمون معلب',itemCalories: 3),
    // SmallCupModel(itemName: 'عصير برتقال طازج ',itemCalories: 59),
    // SmallCupModel(itemName: 'عصير برتقال معلب',itemCalories: 52),
    // SmallCupModel(itemName: 'عصير جريب فروت محلي معلب',itemCalories: 58),
    // SmallCupModel(itemName: 'عصير جريب فروت غير محلي ',itemCalories: 47),
    // SmallCupModel(itemName: 'عصير خوخ معلب',itemCalories: 67),
    // SmallCupModel(itemName: 'عصير كمثري معلب',itemCalories: 75),
    // SmallCupModel(itemName: 'عصير اناناس معلب',itemCalories: 70),
    // SmallCupModel(itemName: 'عصير طماطم معلب',itemCalories: 21),
    // SmallCupModel(itemName: 'عصير جزر معلب',itemCalories: 49),
    //
    // GmsModel(itemName: 'عصير جوافة',itemCalories: 175),
    // GmsModel(itemName: 'عصير مانجو',itemCalories: 110),
    // GmsModel(itemName: 'شراب الفيمتو ',itemCalories: 165),
    //
    // GmsModel(itemName: 'قهوة نسكافية بدون سكر ',itemCalories: 5),
    // GmsModel(itemName: 'قهوة سريعة الذوبان بدون كافيين',itemCalories: 5),
    // GmsModel(itemName: 'شاي بدون سكر ',itemCalories: 1),
    // GmsModel(itemName: 'القهوة الأمريكية',itemCalories: 5),
    //
    // GmsModel(itemName: 'ببسي كولا',itemCalories: 100),
    // GmsModel(itemName: 'دايت ببسي كولا',itemCalories: 0),
    // GmsModel(itemName: 'سفن اب',itemCalories: 90),
    // GmsModel(itemName: 'سبرايت',itemCalories: 96),
    // GmsModel(itemName: 'فانتا',itemCalories: 119),
    // GmsModel(itemName: 'كوكاكولا',itemCalories: 97),
    // GmsModel(itemName: 'دايت كوكاكولا',itemCalories: 1),
    // GmsModel(itemName: 'كريم صودا',itemCalories: 126),
    // GmsModel(itemName: 'مشروبالعنب الغازي ',itemCalories: 107),
    //
    // GmsModel(itemName: 'لحم بقر',itemCalories: 142),
    // GmsModel(itemName: 'بسطرمة - ديك رومي',itemCalories: 40),
    // GmsModel(itemName: 'بابرونب بقر ',itemCalories: 141 ),
    // GmsModel(itemName: 'سلامي - ديك رومي',itemCalories: 56),
    // GmsModel(itemName: 'سلامي - لحم بقر',itemCalories: 72),
    // GmsModel(itemName: 'مارتديلا -لحم بقر',itemCalories: 47),
    // GmsModel(itemName: 'ديك رومي',itemCalories: 57),
    // GmsModel(itemName: 'لحم بقر',itemCalories: 88),
    // GmsModel(itemName: 'لحم ديك رومي',itemCalories: 102),
    // GmsModel(itemName: 'لحم دجاج',itemCalories: 116),
    //
    // GmsModel(itemName: 'بياض البيض (طازج أو مثلج )',itemCalories: 17),
    // GmsModel(itemName: 'صفار البيض الطازج',itemCalories: 59),
    // GmsModel(itemName: 'بيض مسلوق سلق كامل',itemCalories: 79),
    // GmsModel(itemName: 'بيض مقلي',itemCalories: 91),
    // GmsModel(itemName: 'أومليت',itemCalories: 92),
    // GmsModel(itemName: 'أومليت مع جبنة و خضار',itemCalories: 252),
    // GmsModel(itemName: 'بيض بط',itemCalories: 130),
    // GmsModel(itemName: 'بيض وزة',itemCalories: 267),
    // GmsModel(itemName: 'بيض ديك رومي',itemCalories: 135),
    // GmsModel(itemName: 'بيض السمان',itemCalories: 14),
    //
    // GmsModel(itemName: 'جوز',itemCalories: 380),
    // GmsModel(itemName: 'لوز مجفف',itemCalories: 209),
    // GmsModel(itemName: 'كاجو محمص جاف',itemCalories: 160),
    // GmsModel(itemName: 'كاجو محمص بالزيت',itemCalories: 165),
    // GmsModel(itemName: 'بندق محمص جاف',itemCalories: 170),
    // GmsModel(itemName: 'بندق محمص بالزيت',itemCalories: 176),
    // GmsModel(itemName: 'ماش (عدس أخضر)',itemCalories: 215),
    // GmsModel(itemName: 'عدس مطبوخ',itemCalories: 210),
    //
    // GmsModel(itemName: 'مارجرين',itemCalories: 105),
    // GmsModel(itemName: 'زيت زيتون',itemCalories:120),
    // GmsModel(itemName: 'زيت عباد الشمس',itemCalories: 120),
    // GmsModel(itemName: 'دهن غنم',itemCalories: 114),
    // GmsModel(itemName: 'زيت نباتي',itemCalories: 126),
    // GmsModel(itemName: 'دهن بقري',itemCalories: 125),
    // GmsModel(itemName: 'الزبدة',itemCalories: 36),
    // GmsModel(itemName: 'زيت الذرة',itemCalories: 120),
    //
    // GmsModel(itemName: 'تفاح',itemCalories: 81),
    // GmsModel(itemName: 'مشمش',itemCalories: 17),
    // GmsModel(itemName: 'موز',itemCalories: 105),
    // GmsModel(itemName: 'تين',itemCalories: 37),
    // GmsModel(itemName: 'جريب فروت',itemCalories: 38),
    // GmsModel(itemName: 'كرز',itemCalories: 49),
    // GmsModel(itemName: 'افوكادو',itemCalories: 162),
    // GmsModel(itemName: 'عنب',itemCalories: 53),
    // GmsModel(itemName: 'جوافة',itemCalories: 45),
    // GmsModel(itemName: 'كيوي',itemCalories: 46),
    // GmsModel(itemName: 'مانجا',itemCalories: 68),
    // GmsModel(itemName: 'برتقال',itemCalories: 62),
    // GmsModel(itemName: 'بابايا',itemCalories: 117),
    // GmsModel(itemName: 'خوخ',itemCalories: 37),
    // GmsModel(itemName: 'كمثري',itemCalories: 98),
    // GmsModel(itemName: 'اناناس',itemCalories: 42),
    // GmsModel(itemName: 'انجاص',itemCalories: 36),
    // GmsModel(itemName: 'رمان',itemCalories: 110),
    // GmsModel(itemName: 'نكتارين',itemCalories: 67),
    // GmsModel(itemName: 'بطيخ',itemCalories: 26),
    // GmsModel(itemName: 'شمام',itemCalories: 33),
    // GmsModel(itemName: 'فراولة',itemCalories: 23),
    // GmsModel(itemName: 'افندي',itemCalories: 37),
    // GmsModel(itemName: 'توت',itemCalories: 122),
    // GmsModel(itemName: 'بلح (رطب)',itemCalories: 150),
    // GmsModel(itemName: 'اكدنيا',itemCalories: 49),
    // GmsModel(itemName: 'برقوق',itemCalories: 52),
    // GmsModel(itemName: 'ليمون',itemCalories: 17),
    // GmsModel(itemName: 'ليمون حلو',itemCalories: 53),
    // GmsModel(itemName: 'توت اسود',itemCalories: 117),
    // GmsModel(itemName: 'نبق',itemCalories: 9),
    // GmsModel(itemName: 'سفرجل',itemCalories: 60),
    // GmsModel(itemName: 'تمر هندي',itemCalories: 82),
    //
    // GmsModel(itemName: 'مشمش معلب مع ماء و سكر',itemCalories: 111),
    // GmsModel(itemName: 'سلطة الفواكة مع شراب السكر',itemCalories: 94),
    // GmsModel(itemName: 'كرز معلب مع شراب السكر الغليظ',itemCalories: 107),
    // GmsModel(itemName: 'خوخ معلب مع ماء و سكر',itemCalories: 95),
    // GmsModel(itemName: 'كمثري معلب مع ماء و سكر',itemCalories: 94),
    // GmsModel(itemName: 'اناناس معلب مع ماء و سكر',itemCalories: 100),
    //
    // GmsModel(itemName: 'تمر',itemCalories: 26),
    // GmsModel(itemName: 'تين مجفف',itemCalories: 288),
    // GmsModel(itemName: 'كشمش زبيب',itemCalories: 109),
    // GmsModel(itemName: 'انجاص مجفف',itemCalories: 113),
    // GmsModel(itemName: 'مشمش مجفف',itemCalories: 169),
    // GmsModel(itemName: 'حب الهال',itemCalories: 7),
    // GmsModel(itemName: 'فلفل احمر حار مجفف',itemCalories: 13),
    // GmsModel(itemName: 'قرفة',itemCalories: 7),
    // GmsModel(itemName: 'قرنفيل',itemCalories: 6),
    // GmsModel(itemName: 'كمون',itemCalories: 6),
    // GmsModel(itemName: 'زنجبيل(مسحوق)',itemCalories: 1),
    // GmsModel(itemName: 'جذر الزنجبيل',itemCalories: 20),
    // GmsModel(itemName: 'جوز الطيب (مسحوق)',itemCalories: 9),
    // GmsModel(itemName: 'فلفل اسود',itemCalories: 8),
    // GmsModel(itemName: 'جبنة قشقوان',itemCalories: 404),
    // GmsModel(itemName: 'جبن حلوم',itemCalories: 363),
    // GmsModel(itemName: 'قشطة مركزة',itemCalories: 52),
    // GmsModel(itemName: 'قشطة متوسطة',itemCalories: 37),
    // GmsModel(itemName: 'روب(زبادي) كامل الدسم',itemCalories: 141),
    // GmsModel(itemName: 'روب(زبادي)خالي الدسم',itemCalories: 114),
    // GmsModel(itemName: 'لبنة',itemCalories: 105),
    // GmsModel(itemName: 'لبن خاثر',itemCalories: 99),
    // GmsModel(itemName: 'بوطة فانيلا 10%دسم',itemCalories: 135),
    //
    // GmsModel(itemName: 'فانيلا',itemCalories: 240),
    // GmsModel(itemName: 'كاكاو',itemCalories: 280),
    // GmsModel(itemName: 'فراولة',itemCalories: 220),
    //
    // GmsModel(itemName: 'كتف لحم غنم مطبوخ مع دهن',itemCalories: 220),
    // GmsModel(itemName: 'كتف لحم غنم مطبوخ بدون دهن',itemCalories: 135),
    // GmsModel(itemName: 'فخذ لحم غنم محمر مع دهن',itemCalories: 205),
    // GmsModel(itemName: 'فخذ لحم غنم محمر بدون دهن',itemCalories: 140),
    // GmsModel(itemName: 'ضلع مقطع لحم غنم مشوي بدوندهن',itemCalories: 200),
    // GmsModel(itemName: 'ضلع مقطع لحم غنم مع دهن',itemCalories: 307),
    // GmsModel(itemName: 'لحم بقر مطبوخ صدر',itemCalories: 189),
    // GmsModel(itemName: 'كتف لحم بقر بدون دهن',itemCalories: 183),
    // GmsModel(itemName: 'لحم بقر مفروم مطبوخ',itemCalories: 245),
    // GmsModel(itemName: 'شاورما (لحم صافي)',itemCalories: 317),
    // GmsModel(itemName: 'ستيك لحم بقر بدون دهن ',itemCalories: 174),
    // GmsModel(itemName: 'تكة',itemCalories: 133),
    // GmsModel(itemName: 'كباب',itemCalories: 226),
    // GmsModel(itemName: 'كبة محشية',itemCalories: 281),
    // GmsModel(itemName: 'ريش بدون دهن',itemCalories: 182),
    // GmsModel(itemName: 'قلب عجل مطبوخ',itemCalories: 148),
    // GmsModel(itemName: 'كلية عجل مطبوخ',itemCalories: 122),
    // GmsModel(itemName: 'لسان عجل مطبوخ',itemCalories: 241),
    //
    // GmsModel(itemName: 'جزر',itemCalories: 31 ),
    // GmsModel(itemName: 'جزر مطبوخ',itemCalories: 35),
    // GmsModel(itemName: 'زهرة قرنبيط مطبوخ',itemCalories: 15),
    // GmsModel(itemName: 'زهرة قرنبيط غير مطبوخ',itemCalories: 12),
    // GmsModel(itemName: 'خيار مقطع',itemCalories: 7),
    // GmsModel(itemName: 'باذنجان مقلي',itemCalories: 100),
    // GmsModel(itemName: 'باذنجان مطبوخ',itemCalories: 13),
    // GmsModel(itemName: 'فاصوليا خضراء مطبوخة',itemCalories: 20),
    // GmsModel(itemName: 'فاصوليا خضراء معلبة',itemCalories: 25),
    // GmsModel(itemName: 'ملفوف مطبوخ',itemCalories: 16),
    // GmsModel(itemName: 'ملفوف غير مطبوخ',itemCalories: 8),
    // GmsModel(itemName: 'كرفس',itemCalories: 10),
    // GmsModel(itemName: 'ذرة',itemCalories: 77),
    // GmsModel(itemName: 'فطر طازج',itemCalories: 9),
    // GmsModel(itemName: 'فطر معلب',itemCalories: 19),
    // GmsModel(itemName: 'خس',itemCalories: 4),
    // GmsModel(itemName: 'خضار مشكلة (مجموعة مطبوخة)',itemCalories: 54),
    // GmsModel(itemName: 'بامية مقطعة و مطبوخة',itemCalories: 25),
    // GmsModel(itemName: 'بصل طازج مقطع',itemCalories: 27),
    // GmsModel(itemName: 'بصل اخضر مقطع',itemCalories: 16),
    // GmsModel(itemName: 'بزاليا خضراء مطبوخة',itemCalories: 67),
    // GmsModel(itemName: 'فلفل حلو مقطع',itemCalories: 12),
    // GmsModel(itemName: 'فلفل حار',itemCalories: 18),
    // GmsModel(itemName: 'بطاطا مشوية مع القشرة',itemCalories: 220),
    // GmsModel(itemName: 'بطاطا مشوية بدون القشرة',itemCalories: 162),
    // GmsModel(itemName: 'بطاطا مقلية أصابع',itemCalories: 158),
    // GmsModel(itemName: 'لفت (شلغم)مسلوق',itemCalories: 14),
    // GmsModel(itemName: 'جرجير',itemCalories: 2),
    // GmsModel(itemName: 'قرع',itemCalories: 41),
    // GmsModel(itemName: 'فجل (رويد)احمر',itemCalories: 7),
    // GmsModel(itemName: 'فجل (رويد)أحمر الأوراق',itemCalories: 9),
    // GmsModel(itemName: 'سبانغ مقطعة',itemCalories: 6),
    // GmsModel(itemName: 'كوسا مقطعة و مطبوخة',itemCalories: 18),
    // GmsModel(itemName: 'بطاطا حلوة مهروسة',itemCalories: 111),
    // GmsModel(itemName: 'طماطم حمراء',itemCalories: 26),
    // GmsModel(itemName: 'فول اخضر',itemCalories: 73),
    // GmsModel(itemName: 'شمندر',itemCalories: 46),
    // GmsModel(itemName: 'كرنب',itemCalories: 73),
    // GmsModel(itemName: 'كرات',itemCalories: 1),
    // GmsModel(itemName: 'كزبرة',itemCalories: 97),
    // GmsModel(itemName: 'اوراق الحلبة',itemCalories: 25),
    // GmsModel(itemName: 'ثوم',itemCalories: 7),
    // GmsModel(itemName: 'ورق عنب',itemCalories: 146),
    // GmsModel(itemName: 'نعناع',itemCalories: 84),
    // GmsModel(itemName: 'زيتون اسود',itemCalories: 95),
    // GmsModel(itemName: 'زيتون اخضر',itemCalories: 66),
    // GmsModel(itemName: 'بقدونس',itemCalories: 34),
    // GmsModel(itemName: 'بقدونس',itemCalories: 25),
    // GmsModel(itemName: 'فجا ابيض(رويد)',itemCalories: 58),
    // GmsModel(itemName: 'سبانخ',itemCalories: 14),
    // GmsModel(itemName: 'كوسة',itemCalories: 31),
    // GmsModel(itemName: 'كوسة',itemCalories: 40),
    // GmsModel(itemName: 'ريحان',itemCalories: 50),
    // GmsModel(itemName: 'سلق',itemCalories: 32),
    // GmsModel(itemName: 'بقلة',itemCalories: 32),
    // GmsModel(itemName: 'قصب سكر',itemCalories: 82),
    //
    // GmsModel(itemName: 'خبز رقاق',itemCalories: 17),
    // GmsModel(itemName: 'خبز لبناني',itemCalories: 70),
    // GmsModel(itemName: 'خبز تنور (ايراني)',itemCalories: 79),
    // GmsModel(itemName: 'خبز اسمر',itemCalories: 130),
    // GmsModel(itemName: 'مناقيش (خبز مع زعتر)',itemCalories: 208),
    // GmsModel(itemName: 'صمون',itemCalories: 209),
    // GmsModel(itemName: 'بقصم (كعك)',itemCalories: 150),
    // GmsModel(itemName: 'مكرونة بالصلصة',itemCalories: 190),
    // GmsModel(itemName: 'كورن فليكس',itemCalories: 95),
    // GmsModel(itemName: 'خبز فرنسي',itemCalories: 333),
    // GmsModel(itemName: 'بسكويت عادي',itemCalories: 178),
    // GmsModel(itemName: 'رز ابيض مطبوخ حبة طويلة',itemCalories: 131),
    // GmsModel(itemName: 'توست اسمر',itemCalories: 61),
    // GmsModel(itemName: 'توست عادي ابيض',itemCalories: 64),
    // GmsModel(itemName: 'سباجيتي مطبوخ او مكرونة',itemCalories: 99),
    // GmsModel(itemName: 'سباجيتي مطبوخ مع لحم مفروم و طماطم',itemCalories: 110),
    // GmsModel(itemName: 'لزانيا مع صلصة لحم',itemCalories: 154),
    // GmsModel(itemName: 'شعير',itemCalories: 672),
    // GmsModel(itemName: 'مكرونة',itemCalories: 344),
    // GmsModel(itemName: 'نشا الذرة',itemCalories: 471),
    // GmsModel(itemName: 'رز غير مطبوخ',itemCalories: 675),
    // GmsModel(itemName: 'طحين الرز',itemCalories: 354),
    // GmsModel(itemName: 'بلاليط',itemCalories: 99),
    // GmsModel(itemName: 'برغل جريش مطحون',itemCalories: 613),
    // GmsModel(itemName: 'قمح',itemCalories:485),
    // GmsModel(itemName: 'جباتي خبز هندي',itemCalories: 225),
    //
    // GmsModel(itemName: 'فخذ دجاج مشوي بدون جلد',itemCalories: 167),
    // GmsModel(itemName: 'فخذ دجاج مشوي مع جلد',itemCalories: 223),
    // GmsModel(itemName: 'صدر دجاج مشوي بدون جلد',itemCalories: 142),
    // GmsModel(itemName: 'صدر دجاج مشوي مع جلد',itemCalories: 193),
    // GmsModel(itemName: 'صدر دجاج مقلي بدون جلد',itemCalories: 161),
    // GmsModel(itemName: 'اجنحة دجاج مشوي مع الجلد',itemCalories: 99),
    // GmsModel(itemName: 'قطع دجاج مخلية مقلية',itemCalories: 290),
    // GmsModel(itemName: 'قوانص دجاج مقلية ',itemCalories: 238),
    // GmsModel(itemName: 'كبد دجاج مطبوخة',itemCalories: 135),
    // GmsModel(itemName: 'لحم بط محمر بدون جلد ',itemCalories: 173),
    //
    // GmsModel(itemName: 'لحم داكن محمر بدون جلد ',itemCalories: 161),
    // GmsModel(itemName: 'لحم داكن محمر مع جلد ',itemCalories: 190),
    // GmsModel(itemName: 'لحم فاتح محمر بدون جلد',itemCalories: 135),
    // GmsModel(itemName: 'لحم فاتح محمر مع الجلد ',itemCalories: 169),
    //
    // GmsModel(itemName: 'سمك سردين معلب بالزيت',itemCalories: 58),
    // GmsModel(itemName: 'انشوجة معلبة بالزيت',itemCalories: 42),
    // GmsModel(itemName: 'سمك تونة معلب بالماء',itemCalories: 104),
    // GmsModel(itemName: 'سمك تونة معلب بالزيت',itemCalories: 169),
    // GmsModel(itemName: 'سمك سلمون مدخن',itemCalories: 99),
    // GmsModel(itemName: 'سمك مشوي',itemCalories: 136),
    // GmsModel(itemName: 'سمك اصابع بالبقصمات',itemCalories: 228),
    // GmsModel(itemName: 'ربيان مقلي بالبقصمات',itemCalories: 206),
    // GmsModel(itemName: 'سرطان - سلطعون معلب',itemCalories: 84),
    // GmsModel(itemName: 'ام الربيان مطبوخ',itemCalories: 83),
    // GmsModel(itemName: 'محار نئ',itemCalories: 23),
    // GmsModel(itemName: 'محار مقلي',itemCalories: 46),
    // GmsModel(itemName: 'محار مقلي بالبقصمات',itemCalories: 84),
    // GmsModel(itemName: 'كافيار اسود او احمر',itemCalories: 40),
    //
    // GmsModel(itemName: 'باقلاء مسلوقة',itemCalories: 187),
    // GmsModel(itemName: 'لوبيا ناشفة',itemCalories: 349),
    // GmsModel(itemName: 'لوبياء لوبة',itemCalories: 37),
    // GmsModel(itemName: 'حمص نخي مسلوق',itemCalories: 269),
    // GmsModel(itemName: 'طحين (نخي)',itemCalories: 339),
    // GmsModel(itemName: 'عدس',itemCalories: 192),
    // GmsModel(itemName: 'مكسرات مخلوطة مع فول سوداني محمصة جافة',itemCalories: 170),
    // GmsModel(itemName: 'مكسرات مخلوطة محمصة بالزيت',itemCalories: 175),
    // GmsModel(itemName: 'بذور عباد الشمس محمصة جافة',itemCalories: 170),
    // GmsModel(itemName: 'بذور عباد الشمس محمصة بالزيت',itemCalories: 175),
    // GmsModel(itemName: 'فستق محمص جاف',itemCalories: 357),
    // GmsModel(itemName: 'فول سوداني محمص جاف',itemCalories: 165),
    // GmsModel(itemName: 'فول سوداني محمص بالزيت',itemCalories: 170),
    // GmsModel(itemName: 'زبدة الفول السوداني',itemCalories: 95),
    // GmsModel(itemName: 'كستناء محمصة',itemCalories: 44),
    // GmsModel(itemName: 'جوز الهند',itemCalories: 100),
    // GmsModel(itemName: 'جوز الهند مبشور',itemCalories: 59),
    // GmsModel(itemName: 'بذور القرع المحمص',itemCalories: 127),
    // GmsModel(itemName: 'بذور البطيخ المجفف',itemCalories: 158),
    // GmsModel(itemName: 'حلبة جبوب',itemCalories: 102.2),
    // GmsModel(itemName: 'سمسم',itemCalories: 174.16),
    // GmsModel(itemName: 'صنوبر',itemCalories: 172.7),
  ];
}
